// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTnsX3PGcCcHLRHIULe1RPJvXfPhtXJA',
    appId: '1:642517151449:web:bd44036efde91286dc58c8',
    messagingSenderId: '642517151449',
    projectId: 'freequick',
    authDomain: 'freequick.firebaseapp.com',
    storageBucket: 'freequick.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CE69bB6kJkhIdRGyUxXWzH04rQJYqyQ',
    appId: '1:642517151449:android:4a2e4b28223030ecdc58c8',
    messagingSenderId: '642517151449',
    projectId: 'freequick',
    storageBucket: 'freequick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7TUCfI2hmXeVnJ1JbXcnLxVjQH7ybwug',
    appId: '1:642517151449:ios:e19c9130e032d45edc58c8',
    messagingSenderId: '642517151449',
    projectId: 'freequick',
    storageBucket: 'freequick.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7TUCfI2hmXeVnJ1JbXcnLxVjQH7ybwug',
    appId: '1:642517151449:ios:e19c9130e032d45edc58c8',
    messagingSenderId: '642517151449',
    projectId: 'freequick',
    storageBucket: 'freequick.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzTnsX3PGcCcHLRHIULe1RPJvXfPhtXJA',
    appId: '1:642517151449:web:4e9c924e108f5905dc58c8',
    messagingSenderId: '642517151449',
    projectId: 'freequick',
    authDomain: 'freequick.firebaseapp.com',
    storageBucket: 'freequick.firebasestorage.app',
  );
}
